export * from "./Home"
export * from "./Tiers"
export * from "./Eventos"
export * from "./Clips"
export * from "./LiderBoard"
export * from "./PrivacyPolicy"
export * from "./Dashboard"
export * from "./Login"